schoolproject/schoolproject/schoolapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name='school'
urlpatterns = [
    path('',views.demo,name='demo'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('submit',views.submit,name='submit'),
    path('register/',views.register,name='register'),
    path('hello/',views.hello,name='hello'),
    path('form_order',views.form_order,name='form_order')
]

schoolproject/schoolproject/schoolproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('schoolapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

schoolproject/schoolproject/schoolapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Create your models here.
class student(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O','Others'),
    )
    DEPARTMENT_CHOICES = (
        ('CS', 'COMPUTER SCIENCE'),
        ('C', 'COMMERCE'),
        ('E', 'ENGLISH'),
        ('M', 'MATHS'),
        ('S', 'SOCIAL SCIENCE'),
    )
    name=models.CharField(max_length=250,unique=True)
    dob=models.DateField(max_length=8)
    age=models.IntegerField()
    gender=models.CharField(max_length=1,choices=GENDER_CHOICES)
    phone=models.IntegerField()
    email=models.EmailField()
    address=models.TextField()

    class Meta:
        ordering=('name',)
        verbose_name='student'
        verbose_name_plural='students'

    def __str__(self):
        return self.name

schoolproject/schoolproject/schoolapp/forms.py
from django import forms
from .models import student
class schoolForms(forms.ModelForm):
    class Meta:
        model=student
        fields='__all__'

schoolproject/schoolproject/schoolapp/views.py
from django.contrib import messages,auth
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .forms import schoolForms
from .models import student


# Create your views here.
def demo(request):
    return render(request,'index.html')
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        print("username="+username)
        print("Password="+password)
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            print("valid")
            auth.login(request,user)
            return redirect("/hello")
        else:
            print("invalid credentials")
            messages.info(request, "invalid credentials")
            return redirect("/login")
    return render(request,'login.html')
def register(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        conpassword=request.POST['cpassword']
        if password==conpassword :
            if User.objects.filter(username=username).exists():
                messages.info(request,"Username Taken")
                return redirect('/register')
            else:
                user = User.objects.create_user(username=username,password=password)
                print("user created")
                user.save();
                return redirect('/login')
        else:
             messages.info(request,"Password mismatch")
             return redirect('/register')
        return redirect('/')
    return render(request,"register.html")
def hello(request):
    return render(request,'hello.html')

def form_order(request):
    form = schoolForms(request.POST or None)
    #
    if form.is_valid():
         form.save()
    print("hello")
    purpose=request.POST.get('purpose',False)
    # messages.success(request,purpose)
    print(purpose)

        # return redirect('/')
    return render(request,'form_order.html',{'purpose':purpose,'f1':form})

def logout(request):
    auth.logout(request)
    return redirect('/')
def submit(request):
    print("hello")
    purpose = request.POST.get('purpose', False)
    messages.success(request, purpose)

    print(messages)
    return render(request,'message.html',{'messages':messages})

schoolproject/schoolproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/f7748f618e.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div class="container">

{% include 'nav.html' %}
{% block content %} {% endblock %}


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


</div>

</body>
</html>

schoolproject/schoolproject/templates/dropdown.html
<script>
let data = [{
    item: 'Computer Science',
    subitems: ['Software Engineering', 'Artificial Intelligence', 'Machine Learning', 'NLP','Data Mining']
  },
  {
    item: 'Social Science',
    subitems: ['Polictics', 'Humanity']
  },
  {
    item: 'Maths',
    subitems: ['Statics', 'Discrete']
  },
  {
    item: 'English',
    subitems: ['Literature', 'Language']
  },
  {
    item: 'Commerce',
    subitems: ['Accountancy', 'Bussiness']
  },
];


window.onload = function() {
  var itemSel = document.getElementById("first");
  var subitemSel = document.getElementById("second");

  for (var x in data) {
    itemSel.options[itemSel.options.length] = new Option(data[x].item, x);
  }
  itemSel.onchange = function() {
    //empty
    subitemSel.length = 1;
    //display correct values
    for (var y of data[this.value].subitems) {
      subitemSel.options[subitemSel.options.length] = new Option(y, y);
    }
  }
}
</script>
<main>
<div>

    <select id="first" name="first">
      <option value="" selected="selected">Please select Department</option>
    </select>
  </div>
    <br>
  <div>

    <select id="second" name="second">
      <option value="" selected="selected">Please select course</option>
    </select>
  </div>
    </main>

schoolproject/schoolproject/templates/form_order.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
        body
        {background-image:url({% static 'img/form.jpg' %});
        background-size:cover;
        }
        .logo
{
    text-align:right
}
a.link
{
    float:right
    }

 </style>
  {% if user.is_authenticated %}
        <h1 style="color:black;">Hello {{user.username}}</h1>
        <div class="logo">
        <a href="{% url 'school:logout' %}" class="btn btn-primary" >Logout</a>
        </div>
        <form method="POST">
        {% csrf_token%}
        {{f1.as_p}}
        {% include 'dropdown.html' %}
            <br>
        {% include 'purpose.html' %}
        <button class="btn btn-primary" >Submit</button>
         {% if purpose == 'null' %}

            <div class="alert alert-dismissible alert-success">
            <strong>Please select your purpose </strong>

        <a href="/">Return to home page</a>
                {% elif purpose %}
                <div class="alert alert-dismissible alert-success">
                <strong>{{purpose}} confirmed</strong>

                <a class='link' href="/" >Return to home page</a>


    </div>

</form>
{% endif %}
{% endif %}
{% endblock %}

schoolproject/schoolproject/templates/hello.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
<!--        body-->
<!--        {background-image:url({% static 'img/hello.jpg' %});-->
<!--        background-size:cover;-->
<!--        font-size:30px-->
<!--        }-->
body
{
    background-color:#92B7E1;
}
.logo
{
    text-align:right
}

</style>

    {% if user.is_authenticated %}
        <h1 style="color:black;">Hello {{user.username}}</h1>
        <div class="logo">
        <a href="{% url 'school:logout' %}" class="btn btn-primary" >Logout</a>
        </div>
        <div>
            Welcome to Victory college.<br>
            Please fill the below form to place your order<br>
        </div>

             <a href="{% url 'school:form_order' %}" class="btn btn-primary">Order</a>

     {% endif %}

{% endblock %}

schoolproject/schoolproject/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
        body
        {background-image:url({% static 'img/ban.jpg' %});
        background-size:cover;
        }
  </style>

{% endblock %}

schoolproject/schoolproject/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
        body
        {background-image:url({% static 'img/login.jpg' %});
        background-size:cover;
        }
  </style>

<div class="pos">
<form action="" method="POST" >
    {% csrf_token %}
    <h1 style="color:Tomato;">Login</h1>
    <input type="text" name="username" placeholder="Enter your name"><br><br>
    <input type="password" name="password" placeholder="Enter your password"><br><br>
    <button class="btn btn-secondary" href=" {% url 'school:login' %}">Submit</button>

    Don't have an account? <a class="link" href="{% url 'school:register' %}">Register</a>
</form>
    {% for msg in messages %}
    <h2>{{msg}}.Please enter again!</h2>
    {% endfor %}
    </div>
</div>
{% endblock %}

schoolproject/schoolproject/templates/message.html
{% if messages %}

    <div class="alert alert-dismissible alert-success">
      <button type="button" class="close" data-dismiss="alert">
      ×
      </button>
      <strong>{{messages}}</strong>
    </div>


{% else %}
<h1>hello</h1>
{% endif %}

schoolproject/schoolproject/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container-fluid">
      <div class="my_title row">
            <div class="col-9 col-sm-12 col-md-6 col-lg-6">
                  <img src="{% static 'img/logo.png' %}" alt="logoimage">
                  Victory School
            </div>
            <div class="col-9 col-sm-12 col-md-6 col-lg-6">
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'school:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'school:login' %}">Login</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                     Departments
                    </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                     <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science">Computer Science</a></li>
                    <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Mathematics">Mathematics</a></li>
                    <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce">Commerce</a></li>
                    <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Social_science">Social Science</a></li>
                    <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/English_language">English</a></li>
                   </ul>
                </li>
              </ul>
    </div>
  </div>

</nav>

schoolproject/schoolproject/templates/purpose.html
<select id="first" name="purpose">
      <option value="null" selected="selected">Please select the purpose</option>
    <option value="order" >Order</option>
    <option value="return" >Return</option>
    <option value="enquiry">Enquiry</option>
    </select>
<br>
<br>
Materials Provide<br>
 <input type="checkbox" id="1" name="paper" value="paper">
  <label for="1"> Exam papers</label><br>
  <input type="checkbox" id="2" name="pen" value="pen">
  <label for="2"> Pen</label><br>
  <input type="checkbox" id="3" name="book" value="Book">
  <label for="3"> notebook</label><br><br>

schoolproject/schoolproject/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
        body
        {background-image:url({% static 'img/reg.jpg' %});
        background-size:cover;
        }
</style>


<div class='f' style="margin-left:400px;">
<h1 style="margin-left:50px;">You may Register Here..</h1>
<form action=" " method="post" style="margin-left:130px;">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Enter User name"><br><br>

    <input type="password" name="password" placeholder="Enter Password"><br><br>
    <input type="password" name="cpassword" placeholder="Confirm Password"><br><br>
    <br>
    <button class="btn btn-secondary" href=" {% url 'school:register' %}">Submit</button>
    <br>

</form>

    {% for msg in messages %}
    <h2>{{msg}}.Please enter again!</h2>
    {% endfor %}
    </div>
{% endblock %}